# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Hugo

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  pages:
    output: true
    filter: strict
    parse_branch_index: true
    path: content

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config: true

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC

# Input configuration
_inputs:
  text:
    type: markdown
  heading:
    type: textarea
  button_target:
    type: select
    options:
      values: _select_data.button_targets
      value_key: key
      preview:
        text:
          - key: display_name

_select_data:
  button_targets:
    - key: "_self"
      display_name: Same tab
    - key: "_blank"
      display_name: New tab

_structures:
  button:
    values:
      - value:
          button_link:
          button_text:
          button_target:

