# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Customer-card"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  customer:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  customer:
    type: select
    options:
      values: data.customers
      value_key: name
