# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Day"
  description:
  icon: event
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  day:
  loaves: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  loaves:
    type: multiselect
    options:
      values: data.loaves
