# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Classic
  description: Main page hero block with background image or color, and optional CTA button.
  icon: title
  tags:

# Defines the structure of this component, as well as the default values
blueprint:
  title:
  lead:
  background:
    background_image:
    background_color:
  button:
    button_link:
    button_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Body of the Year Bakery
  lead: "Dunedin, NZ"
  background:
    background_image: https://placekitten.com/1500
    background_color: white
  button: 
    button_link: /
    button_text: Contact

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:

